в строке with teradatasql.connect(host=host, user=user, password=password, manage_error_tables=False) as con: 
возникает ошибка UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf1 in position 494: invalid continuation byte

